export { default as MainLogo } from './main-logo.svg';
export { default as MenuIcon } from './menu-icon.svg';
export { default as EditIcon } from './edit-icon.svg';
export { default as HomeIcon } from './home-icon.svg';
export { default as UserIcon } from './user-icon.svg';
export { default as GroupIcon } from './group-icon.svg';
export { default as PhoneIcon } from './phone-icon.svg';
export { default as MailIcon } from './mail-icon.svg';
export { default as LockIcon } from './lock-icon.svg';
export { default as OpenEyeIcon } from './open-eye-icon.svg';
export { default as CloseEyeIcon } from './close-eye-icon.svg';
export { default as BackArrowIcon } from './back-arrow-icon.svg';
export { default as LogoutIcon } from './logout-icon.svg';
export { default as PlusIcon } from './plus-icon.svg';
export { default as AddUserIcon } from './add-user-icon.svg';
export { default as CabinAir } from './cabin-air.svg'
